/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.user;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class User extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3465593909914493304L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"avro.user\",\"fields\":[{\"name\":\"name\",\"type\":[\"string\",\"null\"]},{\"name\":\"favourite_number\",\"type\":[\"int\",\"null\"]},{\"name\":\"favourite_color\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.Integer favourite_number;
  @Deprecated public java.lang.CharSequence favourite_color;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public User() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param favourite_number The new value for favourite_number
   * @param favourite_color The new value for favourite_color
   */
  public User(java.lang.CharSequence name, java.lang.Integer favourite_number, java.lang.CharSequence favourite_color) {
    this.name = name;
    this.favourite_number = favourite_number;
    this.favourite_color = favourite_color;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return favourite_number;
    case 2: return favourite_color;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: favourite_number = (java.lang.Integer)value$; break;
    case 2: favourite_color = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'favourite_number' field.
   * @return The value of the 'favourite_number' field.
   */
  public java.lang.Integer getFavouriteNumber() {
    return favourite_number;
  }

  /**
   * Sets the value of the 'favourite_number' field.
   * @param value the value to set.
   */
  public void setFavouriteNumber(java.lang.Integer value) {
    this.favourite_number = value;
  }

  /**
   * Gets the value of the 'favourite_color' field.
   * @return The value of the 'favourite_color' field.
   */
  public java.lang.CharSequence getFavouriteColor() {
    return favourite_color;
  }

  /**
   * Sets the value of the 'favourite_color' field.
   * @param value the value to set.
   */
  public void setFavouriteColor(java.lang.CharSequence value) {
    this.favourite_color = value;
  }

  /**
   * Creates a new User RecordBuilder.
   * @return A new User RecordBuilder
   */
  public static avro.user.User.Builder newBuilder() {
    return new avro.user.User.Builder();
  }

  /**
   * Creates a new User RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new User RecordBuilder
   */
  public static avro.user.User.Builder newBuilder(avro.user.User.Builder other) {
    return new avro.user.User.Builder(other);
  }

  /**
   * Creates a new User RecordBuilder by copying an existing User instance.
   * @param other The existing instance to copy.
   * @return A new User RecordBuilder
   */
  public static avro.user.User.Builder newBuilder(avro.user.User other) {
    return new avro.user.User.Builder(other);
  }

  /**
   * RecordBuilder for User instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User>
    implements org.apache.avro.data.RecordBuilder<User> {

    private java.lang.CharSequence name;
    private java.lang.Integer favourite_number;
    private java.lang.CharSequence favourite_color;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.user.User.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.favourite_number)) {
        this.favourite_number = data().deepCopy(fields()[1].schema(), other.favourite_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.favourite_color)) {
        this.favourite_color = data().deepCopy(fields()[2].schema(), other.favourite_color);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing User instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.user.User other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.favourite_number)) {
        this.favourite_number = data().deepCopy(fields()[1].schema(), other.favourite_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.favourite_color)) {
        this.favourite_color = data().deepCopy(fields()[2].schema(), other.favourite_color);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public avro.user.User.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public avro.user.User.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'favourite_number' field.
      * @return The value.
      */
    public java.lang.Integer getFavouriteNumber() {
      return favourite_number;
    }

    /**
      * Sets the value of the 'favourite_number' field.
      * @param value The value of 'favourite_number'.
      * @return This builder.
      */
    public avro.user.User.Builder setFavouriteNumber(java.lang.Integer value) {
      validate(fields()[1], value);
      this.favourite_number = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'favourite_number' field has been set.
      * @return True if the 'favourite_number' field has been set, false otherwise.
      */
    public boolean hasFavouriteNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'favourite_number' field.
      * @return This builder.
      */
    public avro.user.User.Builder clearFavouriteNumber() {
      favourite_number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'favourite_color' field.
      * @return The value.
      */
    public java.lang.CharSequence getFavouriteColor() {
      return favourite_color;
    }

    /**
      * Sets the value of the 'favourite_color' field.
      * @param value The value of 'favourite_color'.
      * @return This builder.
      */
    public avro.user.User.Builder setFavouriteColor(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.favourite_color = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'favourite_color' field has been set.
      * @return True if the 'favourite_color' field has been set, false otherwise.
      */
    public boolean hasFavouriteColor() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'favourite_color' field.
      * @return This builder.
      */
    public avro.user.User.Builder clearFavouriteColor() {
      favourite_color = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public User build() {
      try {
        User record = new User();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.favourite_number = fieldSetFlags()[1] ? this.favourite_number : (java.lang.Integer) defaultValue(fields()[1]);
        record.favourite_color = fieldSetFlags()[2] ? this.favourite_color : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
